server:
  servlet:
    context-path: /api
  port: 8081

spring:
  application:
    name: "cards"
  profiles:
    active: ""
  datasource:
    url: jdbc:mysql://localhost:3306/cardsdb
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  # `spring.sql.init.mode` will run `resources/schema.sql`
  sql:
    init:
      mode: always
  config:
    import: "configserver:http://localhost:8071/"

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace