spring:
  application:
    name: cards
  datasource:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  config:
    import: "configserver:http://localhost:8071"
  profiles:
    active: ""

server:
  servlet:
    context-path: /api
  port: 8081

h2:
  tcp:
    enabled: true
    port: 9191
  web:
    enabled: true
    port: 8084