server:
  servlet:
    context-path: /api
  port: 8081

spring:
  application:
    name: "cards"
  profiles:
    active: ""
  datasource:
    url: "jdbc:mysql://localhost:3306/cardsdb"
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  # `spring.sql.init.mode` will run `resources/schema.sql`
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://localhost:8071/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enable: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: "http://localhost:8070/eureka/"

info:
  app:
    name:
      name: "cards"
      description: "Cards App"
      version: "1.0.0"

logging:
  level:
    com:
      momo2x:
        momobank:
          cards: debug
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace