services:
  network-deploy-service:
    networks:
      - momobank-network

  microservices-base-config:
    extends:
      service: network-deploy-service
#    environment:
#      SPRING_RABBITMQ_HOST: rabbitmq
    deploy:
      resources:
        limits:
          memory: 700m

  microservices-configserver-config:
    extends:
      service: microservices-base-config
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  microservices-discovery-config:
    extends:
      service: microservices-configserver-config
    depends_on:
      mysqldb:
        condition: service_healthy
      discoveryserver:
        condition: service_healthy
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discoveryserver:8070/eureka/