services:
  network-deploy-service:
    networks:
      - momobank-network

  microservices-base-config:
    extends:
      service: network-deploy-service
    environment:
      SPRING_RABBITMQ_HOST: "rabbitmq"
    deploy:
      resources:
        limits:
          memory: 700m

  microservices-configserver-config:
    extends:
      service: microservices-base-config
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"
      SPRING_PROFILES_ACTIVE: default
    depends_on:
      configserver:
        condition: service_healthy