services:
  accounts:
    image: "alejoceballos/ms_study_accounts:v1"
    container_name: "accounts"
    ports:
      - "8080:8080"
      - "9090:9090"
      - "8084:8084"
    networks:
      - momobank-network
    deploy:
      resources:
        limits:
          memory: 700m
  cards:
    image: "alejoceballos/ms_study_cards:v1"
    container_name: "cards"
    ports:
      - "8081:8081"
      - "9091:9091"
      - "8085:8085"
    networks:
      - momobank-network
    deploy:
      resources:
        limits:
          memory: 700m
  loans:
    image: "alejoceballos/ms_study_loans:v1"
    container_name: "loans"
    ports:
      - "8082:8082"
      - "9092:9092"
      - "8086:8086"
    networks:
      - momobank-network
    deploy:
      resources:
        limits:
          memory: 700m

networks:
  momobank-network:
    name: momobank-network
    driver: "bridge"