services:
#  rabbitmq:
#    image: rabbitmq:4.0-management
#    hostname: rabbitmq
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    healthcheck:
#      test: rabbitmq-diagnostics check_port_connectivity
#      interval: 10s
#      timeout: 5s
#      retries: 3
#      start_period: 5s
#    extends:
#      file: common-config.yml
#      service: network-deploy-service

  # Check: https://github.com/abagayev/docker-bootstrap-collection/tree/master/mysql-few-databases
  mysqldb:
    image: "mysql:9.1.0"
    container_name: mysqldb
    ports:
      - "3306:3306"
    volumes:
      - ./provision/mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysql", "-u", "root", "-proot", "--execute", "SHOW DATABASES;"]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    extends:
      file: common-config.yml
      service: network-deploy-service

  configserver:
    image: "alejoceballos/ms_study_configserver:v1"
    container_name: configserver
    ports:
      - "8071:8071"
#    depends_on:
#      rabbitmq:
#        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservices-base-config

  eurekaserver:
    image: "alejoceballos/ms_study_eurekaserver:v1"
    container_name: eurekaserver
    ports:
      - "8070:8070"
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservices-configserver-config

  accounts:
    image: alejoceballos/ms_study_accounts:v1
    container_name: accounts
    ports:
      - "8080:8080"
      - "9090:9090"
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysqldb:3306/accountsdb"
    extends:
      file: common-config.yml
      service: microservices-eureka-config

  cards:
    image: alejoceballos/ms_study_cards:v1
    container_name: cards
    ports:
      - "8081:8081"
      - "9091:9091"
      - "8085:8085"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysqldb:3306/cardsdb"
    extends:
      file: common-config.yml
      service: microservices-eureka-config

  loans:
    image: alejoceballos/ms_study_loans:v1
    container_name: loans
    ports:
      - "8082:8082"
      - "9092:9092"
      - "8086:8086"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysqldb:3306/loansdb"
    extends:
      file: common-config.yml
      service: microservices-eureka-config

networks:
  momobank-network:
    name: momobank-network
    driver: bridge

volumes:
  momobank-db-volume:
    driver: local