services:
  rabbitmq:
    image: "rabbitmq:4.0-management"
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    extends:
      file: common-config.yml
      service: network-deploy-service

  configserver:
    image: "alejoceballos/ms_study_configserver:v1"
    container_name: configserver
    ports:
      - "8071:8071"
    depends_on:
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservices-base-config

  accounts:
    image: "alejoceballos/ms_study_accounts:v1"
    container_name: accounts
    ports:
      - "8080:8080"
      - "9090:9090"
      - "8084:8084"
    extends:
      file: common-config.yml
      service: microservices-configserver-config

  cards:
    image: "alejoceballos/ms_study_cards:v1"
    container_name: cards
    ports:
      - "8081:8081"
      - "9091:9091"
      - "8085:8085"
    extends:
      file: common-config.yml
      service: microservices-configserver-config

  loans:
    image: "alejoceballos/ms_study_loans:v1"
    container_name: loans
    ports:
      - "8082:8082"
      - "9092:9092"
      - "8086:8086"
    extends:
      file: common-config.yml
      service: microservices-configserver-config

networks:
  momobank-network:
    name: momobank-network
    driver: bridge